#!/bin/bash
#
# This will install and update packages in the chroot envrioment
#

# Install packages from plan directory
if [[ -d ${PLANS_DIR} ]]; then
  echo "Installing packages listed in the plans directory"

  for FILE in $(ls ${PLANS_DIR}); do

    set_ifs $'\n'

    for PACKAGE in $(cat ${PLANS_DIR}/${FILE} | grep -v '^$\|^\s*\#'); do
      if [[ -f "/${CHROOT_DIR}/${IMPORTS_DIR}/${PACKAGE}" ]]; then
        echo "Installing local package ${PACKAGE}"

        run_chroot_command ${CHROOT_DIR} "dpkg -i --force-overwrite /${IMPORTS_DIR}/${PACKAGE}"
	run_chroot_command ${CHROOT_DIR} "apt-get install -f"

      elif [[ -f "/${CHROOT_DIR}/${IMPORTS_DIR}/${PACKAGE}.deb" ]]; then
	    echo "Installing local DEB ${PACKAGE}"

	    run_chroot_command ${CHROOT_DIR} "dpkg -i --force-overwrite /${IMPORTS_DIR}/${PACKAGE}.deb"
	    run_chroot_command ${CHROOT_DIR} "apt-get install -f"

      else
        echo "APT INSTALL ${PACKAGE}"
			
	    run_chroot_command ${CHROOT_DIR} "apt-get install -y ${PACKAGE}"
      fi

    done

    return_ifs

  done

fi
