#!/bin/bash
#
# This will copy the overlay files into the correct locations
#

if [[ -d ${OVERLAYS_DIR} ]]; then

    echo "Copying overlays to chroot directory"

    pushd ${OVERLAYS_DIR} &> /dev/null

    for DIR in $(ls); do

        run_command "sudo cp -r ${DIR} ${CHROOT_DIR}/."

    done

    popd &> /dev/null

fi
